apiVersion: v1
kind: StatefulSet
metadata:
  name: codis-sentinel
spec:
  replicas: 3
  serviceName: codis-sentinel
  template:
    metadata:
      labels:
        app: codis-sentinel
    spec:
      affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                      - codis-sentinel
                topologyKey: "kubernetes.io/hostname"
      containers:
      - name: codis-sentinel
        image: rebornplay7788/codis-image:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c","redis-sentinel $(CODIS_PATH)/config/sentinel.conf --bind 0.0.0.0 --protected-mode no"]
        lifecycle:
          postStart:
            exec:
              command: ["/bin/bash", "-c", "codis-admin --dashboard=${DASHBOARD_ADDR} --sentinel-add --addr=${POD_IP}:26379 1>/dev/null 2>&1;codis-admin --dashboard=${DASHBOARD_ADDR} --sentinel-resync"]
          preStop:
            exec:
              command: ["/bin/bash", "-c", "codis-admin --dashboard=${DASHBOARD_ADDR} --sentinel-del --addr=${POD_IP}:26379 --force 1>/dev/null 2>&1"]
        env:
        - name: CODIS_PATH
          value: "/gopath/src/github.com/CodisLabs/codis"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DASHBOARD_ADDR
          value: "codis-dashboard:18080"
        ports:
        - containerPort: 26379
          name: sentinel-port
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "0.1"
            memory: 0.1Gi
