apiVersion: v1
kind: Service
metadata:
  labels:
    app: codis-dashboard
  name: codis-dashboard
spec:
  clusterIP: None
  ports:
    - port: 18080
  selector:
    app: codis-dashboard
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: codis-fe
  name: codis-fe
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31080
  selector:
    app: codis-fe
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: codis-proxy
  name: codis-proxy
spec:
  ports:
    - port: 11080
      name: proxy
    - port: 19000
      nodePort: 30679
      name: admin
  type: NodePort
  selector:
    app: codis-proxy
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: codis-server
  name: codis-server
spec:
  clusterIP: None
  ports:
    - port: 6379
  selector:
    app: codis-server
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: codis-sentinel
  name: codis-sentinel
spec:
  clusterIP: None
  ports:
    - port: 26379
  selector:
    app: codis-sentinel